CC = gcc
CFLAGS = -Wall -Werror -g

run_client1:
	$(CC) $(CFLAGS) client.c -o client1 -lrt
	./client1

run_client2:
	$(CC) $(CFLAGS) client.c -o client2 -lrt
	./client2

run_client3:
	$(CC) $(CFLAGS) client.c -o client3 -lrt
	./client3

run_server:
	$(CC) $(CFLAGS) server.c -o server -lrt
	./server


