CC = gcc
CFLAGS = -Wall -Werror -g

run_client1:
	$(CC) $(CFLAGS) client.c -o client1
	./client1

run_client2:
	$(CC) $(CFLAGS) client.c -o client2
	./client2

run_client3:
	$(CC) $(CFLAGS) client.c -o client3
	./client3

run_server:
	$(CC) $(CFLAGS) server.c -o server
	./server


