main:
	gcc -c -Wall main.c
	gcc main.o -o main


testSend:
	./main random1@gmail.com title text

testSend2:
	./main random2@gmail.com title text

testSend3:
	./main random3@gmail.com title text

clean:
	rm *.o main